name=Mecanum-Drive-Arduino
version=1.0.0
author=Akif Bera Öçal
maintainer=Akif Bera Öçal <ocalakif1@gmail.com>
sentence=Library for mecanum wheel control.
paragraph=
category=Device Control
url=https://github.com/SortaHappyDoge/Mecanum-Drive-Arduino
architectures=*
